name: my_first_github_actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: sudo apt install python3 && apt install python3-pytest

    - name: Run PyTest
      run: pytest hello1.py