name: my_first_github_actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run PyTest
      run: python -c 'print("Hello World")'